version: '3.8'

services:
  db:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  web:
#    build: .
#    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
#    volumes:
#      - ".:/app"
#    ports:
#      - "3000:3000"
#    depends_on:
#      - db
#    environment:
#      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
#      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
#      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
#      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
#      RAILS_ENV: ${RAILS_ENV}

volumes:
  db-data:
